### ISSUE TITLE
Project Lazarus

### ISSUE THREAD

**Issue by b-d-m-p** [rmwc/rmwc#758]
This is an issue to list the things we need to do to get RMWC updated in the near future. James, the team at Nykredit and I had a meeting, and will do so weekly to help get through these things listed here. Our goal is to update versions and get RMWC up to date with MDC.

Some of these things might no longer be relevant. We need to go over them once. 

# Roadmap

- [x]  **Get https://github.com/jamesmfriedman/rmwc/pull/746 merged by James**
- [x]  Set up the next meeting for Wed March 2nd at 3:00 PM CET / 9:00 AM EST / 11:00 PM JST
- [x]  Set up a reoccurring check in time (probably same time as above, just need it to be reoccurring)
- [x]  Get James to give us merging rights
- [x] Do Auto release from Github
- [x] Delete all existing GitHub issues
- [x] Add an explanation on front page about closing all the issues - @b-d-m-p 
- [x]  **Upgrade to MWC 6 (done - see [pull request](https://github.com/jamesmfriedman/rmwc/pull/748))** (Merged into Next branch)
- [x] Upgrade to MWC 7 (done - awaiting MWC 6 merge) - @jamesmfriedman (3/18)
- [x] Update createreactapp and storybook @thaestrup (3/25)
- [x] Make introduction video - @jamesmfriedman (3/25)
- [x] Slider update - @jamesmfriedman (4/15)
- [x] Emi will go through and check the v8 components (just the select needs to be fixed she thinks) (3/25)
- [x] Character count bug  https://github.com/jamesmfriedman/rmwc/issues/777 @b-d-m-p (take a look) (4/15)
- [x] Shut down contribution thing
- [x] Take suggestions for a place to donate the money to (To go to Ukraine)
- [x] create react app, and react scripts, typescript, storybook will need to be updated soon or when React 18 is updated. - @thaestrup 
- [x] Update React live (needed for Storybook) - @thaestrup (Test the built production version locally)
- [x] Make MR for the Create React App etc updates - @thaestrup  (by 4/15)
- [x] Upgrade to MWC 8 (ongoing) - @EmiBemi (Match with MDC v8)
- [x] add admins to discord 

- [x] Confirm with @jamesmfriedman about release process (pre release) - Team meeting

- [x] Video contribution guide from James (also talk about issues with MWC theming)
- [ ] Add contributors to the NPM org - @jamesmfriedman 
- [x] Make dependabot auto merge - @jensborch 
- [x] Review Thomas' updates (by 4/15) @jamesmfriedman 
- [x] @EmiBemi Merge #805 and #801 into next and then into master and then make a release branch

- [ ] Send the money to Ukraine, international Red Cross - @jamesmfriedman 
- [x] Get RMWC organization created - @jamesmfriedman 
- [x] Pre-release in Next branch @next or @prerelease
- [x] Release v8
- [x] Have a release party - April 1st? (@EmiBemi is checking with team)
-- [ ] Convert to React Testing Library (verify character count bug with it also) (after v8 release)

- [x] Do release of 6, 7, 8 merges
- [ ] Upgrade to MWC 14 https://github.com/rmwc/rmwc/issues/799 (Started 2021/8/20 about)
- [x]  Rewrite tests for React Testing Library? (see Ricoh team investigation notes below)
- [x]  **Upgrade to React 18 when it is released**
- [x] Verify that sourcemaps of @material dependencies are present and re-enable sourcemap warnings. If not create issue on upstream. (See #779)

# Things Brett is planning on doing
 - [x] Do some pair programming with @EmiBemi  2022/02/22
 - [x] Do more pair programming with @EmiBemi 
 - [ ] Make a guide on how to upgrade MDC versions based on @EmiBemi 's direction in pair programming
- [ ]  Look at the [[bump-to-version-6 branch](https://github.com/Nykredit/rmwc/commits/bump-to-version-6)[](https://github.com/Nykredit/rmwc/commits/bump-to-version-6)](https://github.com/Nykredit/rmwc/commits/bump-to-version-6) and list up bugs, give to Emi - December 16, 2021
- [ ]  Study [https://github.com/Nykredit/rmwc/commits/bump-to-version-6](https://github.com/Nykredit/rmwc/commits/bump-to-version-6) branch
- [ ]  Attempt to upgrade some of the components in the same manner
- [ ]  Rewrite the tests for React Testing Library (if need be)

**Comment by b-d-m-p** [comment]
@jamesmfriedman @EmiBemi Some of this is probably out of date or nonsense, but this is everything I had.

**Comment by b-d-m-p** [comment]
@EmiBemi Who set up the second meeting? Maybe we could make it a reoccurring invite. If it is annoying to do with Zoom, I know that Google Calendar has Google Meet links built in, so we could do it with that or use my Whereby.

**Comment by b-d-m-p** [comment]
@jamesmfriedman @EmiBemi I'm wondering if we could get these people involved. https://github.com/uxpin-merge/rmwc-merge

**Comment by EmiBemi** [comment]
Looks good. I figured out the SSR testing thing. Turns out it was material who introduced a bug. Should be fixed in material 7.

I set up the second meeting. I will try and make it a reoccuring invite in Google.

The uxpin thing doesn't look like something they are working actively on.

**Comment by PeterNjeim** [comment]
Hello, I haven't used RMWC for over 2 years since I've moved away from React, but recently got notified about this repo due to the closing of my issue that I made here. I'm not here to talk about that issue, but to notify you that Material Web is moving to Material You (Material Design 3) components in late 2022: https://github.com/material-components/material-web/issues/3050#issuecomment-1011447013. Don't know if this was part of your plans or not, but just letting you guys know about it.

**Comment by Immortalin** [comment]
Link to Material You: https://m3.material.io/

**Comment by EmiBemi** [comment]
Thank you @PeterNjeim. Several companies are still using RMWC quite heavily, so it is still of interest to make RMWC healthy and get it up to speed with material-component-web.

**Comment by Immortalin** [comment]
@emibemi I think Material You is the next iteration for Material Design, it is not a separate project. Material Web Components will implement Material You eventually.

**Comment by PeterNjeim** [comment]
material-components-web will not be updated past version 2. material-web will be for version 3 and beyond: https://github.com/material-components/material-web/issues/3050#issuecomment-1011464627

**Comment by EmiBemi** [comment]
@Immortalin I thought it would be a seperate project: https://github.com/material-components/material-web

**Comment by jamesmfriedman** [comment]
Agreed that getting RMWC up to date with material 2 is priority. 

Also hearing that M3 won't be available until late 2022 means it will likely be in beta status for a year after that. I personally paid the price of adopting mat web 2 early. 

And who knows, once this project is healthy, maybe it gets forked and RMWC3 becomes a thing.

**Comment by Immortalin** [comment]
Binding Material 3 Web is probably easier since they are written with Lit and there is this first-party library https://www.npmjs.com/package/@lit-labs/react

Less custom code will be needed for RMWC 3

**Comment by jensborch** [comment]
As most of the necessary work for this issue has been completed, I believe it's time to consider closing it. Additionally, we have a separate issue to upgrade to version 14 that is also nearing completion. Any remaining tasks should either be converted into a separate issues or added as tasks on our Kanban board. What do you think @jamesmfriedman and @EmiBemi

**Comment by b-d-m-p** [comment]
Made tasks of remaining items on the project board. Closing this.
